language: python

env:
  global:
    - DUNAMAI_DEV=1
    - DARCS_EMAIL='foo <foo@example.com>'
    - PATH="$PATH:/opt"

before_install:
  - sudo apt-get install -y darcs
  - curl https://www.fossil-scm.org/home/uv/fossil-linux-x64-2.10.tar.gz -o ~/fossil.tgz
  - tar -xvf ~/fossil.tgz -C /opt

install:
  - pip install poetry
  - poetry install

before_script:
  - bzr whoami 'foo <foo@example.com>'

matrix:
  fast_finish: true
  include:
    - python: '3.5'
      script:
        - poetry run pytest --verbose --cov --cov-report term-missing
    - python: '3.6'
      script:
        - poetry run pytest --verbose --cov --cov-report term-missing
    - python: '3.7'
      script:
        - poetry run pytest --verbose --cov --cov-report term-missing
        - poetry run pre-commit run --all-files --show-diff-on-failure
    - python: '3.8'
      script:
        - poetry run pytest --verbose --cov --cov-report term-missing
